In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("../data/solar_weather_dataset.csv")

df.head()

,timestamp,temperature,humidity,cloud_cover,wind_speed,precipitation,solar_output
0,2024-01-01 00:00:00,18.496714,58.617357,56.192213,8.046060,0.082923,0.000000
1,2024-01-01 01:00:00,22.167403,67.674347,28.263140,6.085120,0.000000,0.000000
2,2024-01-01 02:00:00,23.241962,40.867198,0.000000,3.875425,0.000000,6.284947
3,2024-01-01 03:00:00,24.163044,45.876963,76.641219,4.548447,0.233764,0.000000
4,2024-01-01 04:00:00,26.115871,61.109226,11.225161,5.751396,0.000000,0.000000

In [3]:
df["timestamp"] = pd.to_datetime(df["timestamp"])

In [4]:
df["hour"] = df["timestamp"].dt.hour

df["day_of_week"] = df["timestamp"].dt.dayofweek

df["is_weekend"] = df["day_of_week"].isin([5,6]).astype(int)

df.head()

,timestamp,temperature,humidity,cloud_cover,wind_speed,precipitation,solar_output,hour,day_of_week,is_weekend
0,2024-01-01 00:00:00,18.496714,58.617357,56.192213,8.046060,0.082923,0.000000,0,0,0
1,2024-01-01 01:00:00,22.167403,67.674347,28.263140,6.085120,0.000000,0.000000,1,0,0
2,2024-01-01 02:00:00,23.241962,40.867198,0.000000,3.875425,0.000000,6.284947,2,0,0
3,2024-01-01 03:00:00,24.163044,45.876963,76.641219,4.548447,0.233764,0.000000,3,0,0
4,2024-01-01 04:00:00,26.115871,61.109226,11.225161,5.751396,0.000000,0.000000,4,0,0

In [5]:
df["sin_hour"] = np.sin(2 * np.pi * df["hour"] / 24)

df["cos_hour"] = np.cos(2 * np.pi * df["hour"] / 24)

In [6]:
df["temp_cloud_interaction"] = df["temperature"] * (1 - df["cloud_cover"]/100)

In [7]:
df["rolling_temp"] = df["temperature"].rolling(3).mean()

In [8]:
df["lag_solar"] = df["solar_output"].shift(1)

In [9]:
df = df.fillna(0)

In [10]:
df.head()

,timestamp,temperature,humidity,cloud_cover,wind_speed,precipitation,solar_output,hour,day_of_week,is_weekend,sin_hour,cos_hour,temp_cloud_interaction,rolling_temp,lag_solar
0,2024-01-01 00:00:00,18.496714,58.617357,56.192213,8.046060,0.082923,0.000000,0,0,0,0.000000,1.000000,8.103001,0.000000,0.000000
1,2024-01-01 01:00:00,22.167403,67.674347,28.263140,6.085120,0.000000,0.000000,1,0,0,0.258819,0.965926,15.902199,0.000000,0.000000
2,2024-01-01 02:00:00,23.241962,40.867198,0.000000,3.875425,0.000000,6.284947,2,0,0,0.500000,0.866025,23.241962,21.302027,0.000000
3,2024-01-01 03:00:00,24.163044,45.876963,76.641219,4.548447,0.233764,0.000000,3,0,0,0.707107,0.707107,5.644192,23.190803,6.284947
4,2024-01-01 04:00:00,26.115871,61.109226,11.225161,5.751396,0.000000,0.000000,4,0,0,0.866025,0.500000,23.184323,24.506959,0.000000

In [11]:
df.to_csv("../data/processed_solar_data.csv", index=False)

print("Processed dataset saved!")

Processed dataset saved!